### ISSUE TITLE
Cannot run Kinesis apps due to "Reached end of STDIN of child process for shard"

### ISSUE THREAD

**Issue by czchen** [awslabs/amazon-kinesis-client-python#5]
Hi,

We are developing a Kinesis app with this python library. However, during developing, we encounter an exception `java.util.concurrent.ExecutionException: java.lang.RuntimeException: Reached end of STDIN of child process for shard shardId-000000000000 so won't be able to return a message.` which stops our Kinesis app. The python script we used is good because it works before, and we don't understand the meaning of this error message. Any idea of this error message?

Our EC2 instance runs three Kinesis apps by the following command. The apps work on different Kinesis stream, and only one of the apps has this problem.

```
$(./amazon_kclpy_helper.py -j $(which java) -p app_1.properties --print_command)
$(./amazon_kclpy_helper.py -j $(which java) -p app_2.properties --print_command)
$(./amazon_kclpy_helper.py -j $(which java) -p app_3.properties --print_command)
```

The following is console output for broken Kinesis apps.

```
Dec 11, 2014 10:07:26 AM com.amazonaws.services.kinesis.multilang.MultiLangProtocol waitForStatusMessage
SEVERE: Failed to get status message for initialize action for shard shardId-000000000000
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Reached end of STDIN of child process for shard shardId-000000000000 so won't be able to return a message.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.amazonaws.services.kinesis.multilang.MultiLangProtocol.waitForStatusMessage(MultiLangProtocol.java:141)
        at com.amazonaws.services.kinesis.multilang.MultiLangProtocol.waitForStatusMessage(MultiLangProtocol.java:116)
        at com.amazonaws.services.kinesis.multilang.MultiLangProtocol.initialize(MultiLangProtocol.java:70)
        at com.amazonaws.services.kinesis.multilang.MultiLangRecordProcessor.initialize(MultiLangRecordProcessor.java:131)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:74)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:48)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Reached end of STDIN of child process for shard shardId-000000000000 so won't be able to return a message.
        at com.amazonaws.services.kinesis.multilang.GetNextMessageTask.returnAfterEndOfInput(GetNextMessageTask.java:84)
        at com.amazonaws.services.kinesis.multilang.GetNextMessageTask.returnAfterEndOfInput(GetNextMessageTask.java:31)
        at com.amazonaws.services.kinesis.multilang.LineReaderTask.call(LineReaderTask.java:70)
        ... 4 more

Dec 11, 2014 10:07:26 AM com.amazonaws.services.kinesis.multilang.MultiLangRecordProcessor stopProcessing
SEVERE: Encountered an error while trying to initialize record processor
java.lang.RuntimeException: Failed to initialize child process
        at com.amazonaws.services.kinesis.multilang.MultiLangRecordProcessor.initialize(MultiLangRecordProcessor.java:132)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:74)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:48)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:23)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Dec 11, 2014 10:07:26 AM com.amazonaws.services.kinesis.multilang.LineReaderTask call
INFO: Stopping: Reading STDERR for shardId-000000000000
```

**Comment by kunalkushwah** [comment]
I am getting the same exception. While the app ran successfully for some time, it crashed throwing the aforementioned exception. Basically what does it infer when it says "reached end of STDIN of child process" ?

**Comment by pfifer** [comment]
This exception indicates that the child Python process is exiting for some reason.  Usually getting the STDERR should allow you to see messages from the Python record processor.

**Comment by loweehahn** [comment]
I had this error message too. In my case, I made a typo for my S3 bucket name.

**Comment by timvlaer** [comment]
I hit this exception too. 

I do get other logging of my python process so I am rather sure there's no python exception hidden somewhere. 

I wonder if the initialisation times out somehow. I have to load some models in my consumer, so this takes quite some time. It's however not clear to me if there is a setting that I can use to configure a timeout interval for both initialization and processing...
