### ISSUE TITLE
Cannot Override DynamoDB Endpoint

### ISSUE THREAD

**Issue by dnk8n** [awslabs/amazon-kinesis-client-python#52]
I am using kinesalite to run test automation. I was able to easily set the kinesalite endpoint for the kinesis stream producer (a modification of sample_kinesis_wordputter.py) by using **boto.kinesis.layer1.KinesisConnection(**kwargs)**

When performing Kinesis consumer operations against kinesalite (using KCLpy), the KCL checkpointer writes lease tables to AWS's DynamoDB. I want it to do this against a local dynalite server instead. This would require that KCLpy allow to specify an endpoint for DynamoDB.

I haven't found any documentation about anything analagous to KinesisConnection. Is there?

**Comment by pfifer** [comment]
You should be able to override the DynamoDB endpoint by setting `dynamoDBEndpoint = <your endpoint>` in your properties file.

Let me know if that works.

**Comment by dnk8n** [comment]
Thank you, pfifer for your comment. It worked but now I am struggling with a different issue (I will log a seperate issue if needs be but at the moment I don't think it is an issue for you or your documentation).

For those that stumble upon this in the future, once the local dynamo db endpoint is defined, it will also require the kinesis endpoint to be defined, then if using kinesalite, it will fail due to the Java SDK sending CBOR by default instead of json. I updated the sample.properties to include the following (by default, I do still use AWS, hence why the relevant lines are commented out):

`# Used by the KCL as the DynamoDB endpoint for this applications. Particularly
# useful for local development
#dynamoDBEndpoint = http://localhost:7002

# The KCL defaults to us-east-1. Values for 'regionName' or 'kinesisEndpoint'
# can override this, the latter value overriding the former. 'kinesisEndpoint'
# is used by the KCL as the Kinesis endpoint for this applications. Particularly
# useful for local development.
# Note: For local developmant, AWS_CBOR_DISABLE=1 is required
regionName = us-west-2
#kinesisEndpoint = http://localhost:4567`

**Comment by dnk8n** [comment]
Still struggling to find where I can define the "AWS_CBOR_DISABLE=1" when using the python kcl... any insight?

**Comment by dnk8n** [comment]
This issue is closed as far as I am concerned. If anyone stumbles upon this in the future and can tell me where to set AWS_CBOR_DISABLE=1 in terms of the python version of the kinesis client library, please do get in touch! Thanks.

**Comment by pfifer** [comment]
Sorry I haven't had a chance to respond, but the flag can be set as an environment variable `export AWS_CBOR_DISABLE=1` or add `-Dcom.amazonaws.sdk.disableCbor=1` to the java command line in your start script.

[This is the code to check the flags](https://github.com/aws/aws-sdk-java/blob/895d76c82113b35b60bc6e4c4271e44fb362252a/aws-java-sdk-core/src/main/java/com/amazonaws/SDKGlobalConfiguration.java#L283), and all that is required is the either the environment variable, or system property to be set.

**Comment by jl-DaDar** [comment]
I keep on getting this error below when using amazon_kcl with local kinesalite and dynamodb....
any idea?


com.amazonaws.services.kinesis.model.InvalidArgumentException: StartingSequenceNumber 49577534419816769660097426182217450184892176975439855618 used in GetShardIterator on shard shardId-000000000000 in stream boom_app_stream_local under account 000000000000 is invalid because it did not come from this stream. (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidArgumentException; Request ID: 187f0750-cd2d-11e7-9c68-19d0b050d283)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1377)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:923)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:453)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:415)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:1998)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:1968)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.getShardIterator(AmazonKinesisClient.java:1081)
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getIterator(KinesisProxy.java:291)
	at com.amazonaws.services.kinesis.clientlibrary.proxies.MetricsCollectingKinesisProxyDecorator.getIterator(MetricsCollectingKinesisProxyDecorator.java:124)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.getIterator(KinesisDataFetcher.java:140)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.advanceIteratorTo(KinesisDataFetcher.java:120)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.initialize(KinesisDataFetcher.java:91)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:80)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jl-DaDar** [comment]
looks like the dynamoDBEndpoint setting did not overwrite the dynamodb endpoint. It is still using production dynamodb
